[MeasureAudioRaw0]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1
Channel=Avg

[MeasureAudioRaw1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2
Channel=Avg

[MeasureAudioRaw2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3
Channel=Avg

[MeasureAudioRaw3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4
Channel=Avg

[MeasureAudioRaw4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5
Channel=Avg

[MeasureAudioRaw5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6
Channel=Avg

[MeasureAudioRaw6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7
Channel=Avg

[MeasureAudioRaw7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8
Channel=Avg

[MeasureAudioRaw8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9
Channel=Avg

[MeasureAudioRaw9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10
Channel=Avg

[MeasureAudioRaw10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11
Channel=Avg

[MeasureAudioRaw11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12
Channel=Avg

[MeasureAudioRaw12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13
Channel=Avg

[MeasureAudioRaw13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14
Channel=Avg

[MeasureAudioRaw14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15
Channel=Avg

[MeasureAudioRaw15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16
Channel=Avg

[MeasureAudioRaw16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17
Channel=Avg

[MeasureAudioRaw17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18
Channel=Avg

[MeasureAudioRaw18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19
Channel=Avg

[MeasureAudioRaw19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20
Channel=Avg

[MeasureAudioRaw20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21
Channel=Avg

[MeasureAudioRaw21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22
Channel=Avg

[MeasureAudioRaw22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23
Channel=Avg

[MeasureAudioRaw23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24
Channel=Avg

[MeasureAudioRaw24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25
Channel=Avg

[MeasureAudioRaw25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26
Channel=Avg

[MeasureAudioRaw26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27
Channel=Avg

[MeasureAudioRaw27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28
Channel=Avg

[MeasureAudioRaw28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29
Channel=Avg

[MeasureAudioRaw29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30
Channel=Avg

[MeasureAudioRaw30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31
Channel=Avg

[MeasureAudioRaw31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32
Channel=Avg

[MeasureAudioRaw32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33
Channel=Avg

[MeasureAudioRaw33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34
Channel=Avg

[MeasureAudioRaw34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35
Channel=Avg

[MeasureAudioRaw35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36
Channel=Avg

[MeasureAudioRaw36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37
Channel=Avg

[MeasureAudioRaw37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38
Channel=Avg

[MeasureAudioRaw38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39
Channel=Avg

[MeasureAudioRaw39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40
Channel=Avg

[MeasureAudioRaw40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41
Channel=Avg

[MeasureAudioRaw41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42
Channel=Avg

[MeasureAudioRaw42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43
Channel=Avg

[MeasureAudioRaw43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44
Channel=Avg

[MeasureAudioRaw44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45
Channel=Avg

[MeasureAudioRaw45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46
Channel=Avg

[MeasureAudioRaw46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47
Channel=Avg

[MeasureAudioRaw47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48
Channel=Avg

[MeasureAudioRaw48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49
Channel=Avg

[MeasureAudioRaw49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50
Channel=Avg

[MeasureAudioRaw50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51
Channel=Avg

[MeasureAudioRaw51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52
Channel=Avg

[MeasureAudioRaw52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53
Channel=Avg

[MeasureAudioRaw53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54
Channel=Avg

[MeasureAudioRaw54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55
Channel=Avg

[MeasureAudioRaw55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56
Channel=Avg

[MeasureAudioRaw56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57
Channel=Avg

[MeasureAudioRaw57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58
Channel=Avg

[MeasureAudioRaw58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59
Channel=Avg

[MeasureAudioRaw59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60
Channel=Avg

[MeasureAudioRaw60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61
Channel=Avg

[MeasureAudioRaw61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62
Channel=Avg

[MeasureAudioRaw62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63
Channel=Avg

[MeasureAudioRaw63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64
Channel=Avg

[MeasureAudioRaw64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65
Channel=Avg

[MeasureAudioRaw65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66
Channel=Avg

[MeasureAudioRaw66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67
Channel=Avg

[MeasureAudioRaw67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68
Channel=Avg

[MeasureAudioRaw68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69
Channel=Avg

[MeasureAudioRaw69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70
Channel=Avg

[MeasureAudioRaw70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71
Channel=Avg

[MeasureAudioRaw71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72
Channel=Avg

[MeasureAudioRaw72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73
Channel=Avg

[MeasureAudioRaw73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74
Channel=Avg

[MeasureAudioRaw74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75
Channel=Avg

[MeasureAudioRaw75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76
Channel=Avg

[MeasureAudioRaw76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77
Channel=Avg

[MeasureAudioRaw77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78
Channel=Avg

[MeasureAudioRaw78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79
Channel=Avg

[MeasureAudioRaw79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80
Channel=Avg

[MeasureAudioRaw80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81
Channel=Avg

[MeasureAudioRaw81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82
Channel=Avg

[MeasureAudioRaw82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83
Channel=Avg

[MeasureAudioRaw83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84
Channel=Avg

[MeasureAudioRaw84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85
Channel=Avg

[MeasureAudioRaw85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86
Channel=Avg

[MeasureAudioRaw86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87
Channel=Avg

[MeasureAudioRaw87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88
Channel=Avg

[MeasureAudioRaw88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89
Channel=Avg

[MeasureAudioRaw89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=90
Channel=Avg

[MeasureAudioRaw90]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=91
Channel=Avg

[MeasureAudioRaw91]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=92
Channel=Avg

[MeasureAudioRaw92]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=93
Channel=Avg

[MeasureAudioRaw93]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=94
Channel=Avg

[MeasureAudioRaw94]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=95
Channel=Avg

[MeasureAudioRaw95]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=96
Channel=Avg

[MeasureAudioRaw96]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=97
Channel=Avg

[MeasureAudioRaw97]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=98
Channel=Avg

[MeasureAudioRaw98]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=99
Channel=Avg

[MeasureAudioRaw99]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=100
Channel=Avg

[MeasureAudioRaw100]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=101
Channel=Avg
