[MeasureAudioRaw0]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=90
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw90]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=91
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw91]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=92
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw92]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=93
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw93]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=94
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw94]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=95
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw95]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=96
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw96]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=97
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw97]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=98
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw98]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=99
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw99]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=100
Channel=Avg
Group=RawAudioMeasures

[MeasureAudioRaw100]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=101
Channel=Avg
Group=RawAudioMeasures
