[MeterBar0]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
[MeterBar1]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
[MeterBar2]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
[MeterBar3]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
[MeterBar4]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
[MeterBar5]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
[MeterBar6]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
[MeterBar7]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
[MeterBar8]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
[MeterBar9]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
[MeterBar10]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
[MeterBar11]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]
[MeterBar12]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed12
TransformationMatrix=[Matrix]
[MeterBar13]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed13
TransformationMatrix=[Matrix]
[MeterBar14]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed14
TransformationMatrix=[Matrix]
[MeterBar15]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed15
TransformationMatrix=[Matrix]
[MeterBar16]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed16
TransformationMatrix=[Matrix]
[MeterBar17]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed17
TransformationMatrix=[Matrix]
[MeterBar18]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed18
TransformationMatrix=[Matrix]
[MeterBar19]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed19
TransformationMatrix=[Matrix]
[MeterBar20]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed20
TransformationMatrix=[Matrix]
[MeterBar21]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed21
TransformationMatrix=[Matrix]
[MeterBar22]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed22
TransformationMatrix=[Matrix]
[MeterBar23]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed23
TransformationMatrix=[Matrix]
[MeterBar24]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed24
TransformationMatrix=[Matrix]
[MeterBar25]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed25
TransformationMatrix=[Matrix]
[MeterBar26]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed26
TransformationMatrix=[Matrix]
[MeterBar27]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed27
TransformationMatrix=[Matrix]
[MeterBar28]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed28
TransformationMatrix=[Matrix]
[MeterBar29]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed29
TransformationMatrix=[Matrix]
[MeterBar30]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed30
TransformationMatrix=[Matrix]
[MeterBar31]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed31
TransformationMatrix=[Matrix]
[MeterBar32]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed32
TransformationMatrix=[Matrix]
[MeterBar33]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed33
TransformationMatrix=[Matrix]
[MeterBar34]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed34
TransformationMatrix=[Matrix]
[MeterBar35]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed35
TransformationMatrix=[Matrix]
[MeterBar36]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed36
TransformationMatrix=[Matrix]
[MeterBar37]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed37
TransformationMatrix=[Matrix]
[MeterBar38]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed38
TransformationMatrix=[Matrix]
[MeterBar39]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed39
TransformationMatrix=[Matrix]
[MeterBar40]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed40
TransformationMatrix=[Matrix]
[MeterBar41]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed41
TransformationMatrix=[Matrix]
[MeterBar42]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed42
TransformationMatrix=[Matrix]
[MeterBar43]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed43
TransformationMatrix=[Matrix]
[MeterBar44]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed44
TransformationMatrix=[Matrix]
[MeterBar45]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed45
TransformationMatrix=[Matrix]
[MeterBar46]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed46
TransformationMatrix=[Matrix]
[MeterBar47]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed47
TransformationMatrix=[Matrix]
[MeterBar48]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed48
TransformationMatrix=[Matrix]
[MeterBar49]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed49
TransformationMatrix=[Matrix]
[MeterBar50]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed50
TransformationMatrix=[Matrix]
[MeterBar51]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed51
TransformationMatrix=[Matrix]
[MeterBar52]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed52
TransformationMatrix=[Matrix]
[MeterBar53]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed53
TransformationMatrix=[Matrix]
[MeterBar54]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed54
TransformationMatrix=[Matrix]
[MeterBar55]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed55
TransformationMatrix=[Matrix]
[MeterBar56]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed56
TransformationMatrix=[Matrix]
[MeterBar57]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed57
TransformationMatrix=[Matrix]
[MeterBar58]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed58
TransformationMatrix=[Matrix]
[MeterBar59]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed59
TransformationMatrix=[Matrix]
[MeterBar60]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed60
TransformationMatrix=[Matrix]
[MeterBar61]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed61
TransformationMatrix=[Matrix]
[MeterBar62]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed62
TransformationMatrix=[Matrix]